/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ArticleId = IDL.Nat;
export const EdukasiId = IDL.Nat;
export const EventId = IDL.Nat;
export const PengajuanProdukId = IDL.Nat;
export const PhotoId = IDL.Nat;
export const ProdukId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminSessionId = IDL.Nat;
export const Article = IDL.Record({
  'id' : ArticleId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Nat,
  'author' : IDL.Text,
});
export const Edukasi = IDL.Record({
  'id' : EdukasiId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Nat,
  'author' : IDL.Text,
  'image' : IDL.Opt(IDL.Text),
});
export const MemberId = IDL.Nat;
export const MemberIdNumber = IDL.Text;
export const MemberProfile = IDL.Record({
  'id' : MemberId,
  'verified' : IDL.Bool,
  'contact' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'businessName' : IDL.Text,
  'description' : IDL.Text,
  'website' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'category' : IDL.Text,
  'products' : IDL.Vec(IDL.Text),
  'memberIdNumber' : IDL.Opt(MemberIdNumber),
});
export const PengajuanProduk = IDL.Record({
  'id' : PengajuanProdukId,
  'namaUsaha' : IDL.Text,
  'foto' : IDL.Opt(IDL.Text),
  'kategori' : IDL.Text,
  'hubungiSelanjutnya' : IDL.Opt(IDL.Text),
});
export const Photo = IDL.Record({
  'id' : PhotoId,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'category' : IDL.Text,
  'uploadDate' : IDL.Nat,
});
export const ProdukAnggota = IDL.Record({
  'id' : ProdukId,
  'namaUsaha' : IDL.Text,
  'foto' : IDL.Opt(IDL.Text),
  'kategori' : IDL.Text,
  'hubungiSelanjutnya' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const Event = IDL.Record({
  'id' : EventId,
  'title' : IDL.Text,
  'date' : IDL.Nat,
  'description' : IDL.Text,
  'isUpcoming' : IDL.Bool,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addArticle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ArticleId], []),
  'addEdukasi' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [EdukasiId],
      [],
    ),
  'addEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [EventId],
      [],
    ),
  'addPengajuanProduk' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [PengajuanProdukId],
      [],
    ),
  'addPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [PhotoId], []),
  'addProdukAnggota' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [ProdukId],
      [],
    ),
  'approvePengajuanProduk' : IDL.Func([PengajuanProdukId], [ProdukId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEdukasi' : IDL.Func([EdukasiId], [], []),
  'deleteProdukAnggota' : IDL.Func([ProdukId], [], []),
  'editEdukasi' : IDL.Func(
      [EdukasiId, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'editProdukAnggota' : IDL.Func(
      [ProdukId, IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'endAdminSession' : IDL.Func([AdminSessionId], [], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllEdukasi' : IDL.Func([], [IDL.Vec(Edukasi)], ['query']),
  'getAllMemberProfiles' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
  'getAllPengajuanProduk' : IDL.Func([], [IDL.Vec(PengajuanProduk)], ['query']),
  'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getAllProdukAnggota' : IDL.Func([], [IDL.Vec(ProdukAnggota)], ['query']),
  'getAnggotaListByCategorySorted' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MemberProfile)],
      ['query'],
    ),
  'getArticlesByDate' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEdukasiByDate' : IDL.Func([], [IDL.Vec(Edukasi)], ['query']),
  'getEventsByDate' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getEventsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
  'getMemberProfilesByBusinessName' : IDL.Func(
      [],
      [IDL.Vec(MemberProfile)],
      ['query'],
    ),
  'getMemberProfilesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MemberProfile)],
      ['query'],
    ),
  'getMemberProfilesByCategorySorted' : IDL.Func(
      [],
      [IDL.Vec(MemberProfile)],
      ['query'],
    ),
  'getMembersForAdmin' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
  'getPastEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getPengajuanByKategori' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PengajuanProduk)],
      ['query'],
    ),
  'getPengajuanByKategoriSorted' : IDL.Func(
      [],
      [IDL.Vec(PengajuanProduk)],
      ['query'],
    ),
  'getPengajuanByNamaUsahaSorted' : IDL.Func(
      [],
      [IDL.Vec(PengajuanProduk)],
      ['query'],
    ),
  'getPhotosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Photo)], ['query']),
  'getPhotosByUploadDate' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getProdukByKategori' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProdukAnggota)],
      ['query'],
    ),
  'getProdukByKategoriSorted' : IDL.Func(
      [],
      [IDL.Vec(ProdukAnggota)],
      ['query'],
    ),
  'getProdukByNamaUsahaSorted' : IDL.Func(
      [],
      [IDL.Vec(ProdukAnggota)],
      ['query'],
    ),
  'getSortedAnggotaList' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
  'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerMember' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [MemberId],
      [],
    ),
  'rejectPengajuanProduk' : IDL.Func([PengajuanProdukId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchAnggota' : IDL.Func([IDL.Text], [IDL.Vec(MemberProfile)], ['query']),
  'searchMemberProfilesByBusinessName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MemberProfile)],
      ['query'],
    ),
  'startAdminSession' : IDL.Func([IDL.Text, IDL.Text], [AdminSessionId], []),
  'updateMemberIdNumber' : IDL.Func([MemberId, IDL.Text], [], []),
  'validateAdminSession' : IDL.Func([AdminSessionId], [IDL.Bool], ['query']),
  'verifyMember' : IDL.Func([MemberId, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ArticleId = IDL.Nat;
  const EdukasiId = IDL.Nat;
  const EventId = IDL.Nat;
  const PengajuanProdukId = IDL.Nat;
  const PhotoId = IDL.Nat;
  const ProdukId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminSessionId = IDL.Nat;
  const Article = IDL.Record({
    'id' : ArticleId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Nat,
    'author' : IDL.Text,
  });
  const Edukasi = IDL.Record({
    'id' : EdukasiId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Nat,
    'author' : IDL.Text,
    'image' : IDL.Opt(IDL.Text),
  });
  const MemberId = IDL.Nat;
  const MemberIdNumber = IDL.Text;
  const MemberProfile = IDL.Record({
    'id' : MemberId,
    'verified' : IDL.Bool,
    'contact' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'businessName' : IDL.Text,
    'description' : IDL.Text,
    'website' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'category' : IDL.Text,
    'products' : IDL.Vec(IDL.Text),
    'memberIdNumber' : IDL.Opt(MemberIdNumber),
  });
  const PengajuanProduk = IDL.Record({
    'id' : PengajuanProdukId,
    'namaUsaha' : IDL.Text,
    'foto' : IDL.Opt(IDL.Text),
    'kategori' : IDL.Text,
    'hubungiSelanjutnya' : IDL.Opt(IDL.Text),
  });
  const Photo = IDL.Record({
    'id' : PhotoId,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'category' : IDL.Text,
    'uploadDate' : IDL.Nat,
  });
  const ProdukAnggota = IDL.Record({
    'id' : ProdukId,
    'namaUsaha' : IDL.Text,
    'foto' : IDL.Opt(IDL.Text),
    'kategori' : IDL.Text,
    'hubungiSelanjutnya' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const Event = IDL.Record({
    'id' : EventId,
    'title' : IDL.Text,
    'date' : IDL.Nat,
    'description' : IDL.Text,
    'isUpcoming' : IDL.Bool,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addArticle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ArticleId], []),
    'addEdukasi' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [EdukasiId],
        [],
      ),
    'addEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [EventId],
        [],
      ),
    'addPengajuanProduk' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [PengajuanProdukId],
        [],
      ),
    'addPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [PhotoId], []),
    'addProdukAnggota' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [ProdukId],
        [],
      ),
    'approvePengajuanProduk' : IDL.Func([PengajuanProdukId], [ProdukId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEdukasi' : IDL.Func([EdukasiId], [], []),
    'deleteProdukAnggota' : IDL.Func([ProdukId], [], []),
    'editEdukasi' : IDL.Func(
        [EdukasiId, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'editProdukAnggota' : IDL.Func(
        [ProdukId, IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'endAdminSession' : IDL.Func([AdminSessionId], [], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllEdukasi' : IDL.Func([], [IDL.Vec(Edukasi)], ['query']),
    'getAllMemberProfiles' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
    'getAllPengajuanProduk' : IDL.Func(
        [],
        [IDL.Vec(PengajuanProduk)],
        ['query'],
      ),
    'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getAllProdukAnggota' : IDL.Func([], [IDL.Vec(ProdukAnggota)], ['query']),
    'getAnggotaListByCategorySorted' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MemberProfile)],
        ['query'],
      ),
    'getArticlesByDate' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEdukasiByDate' : IDL.Func([], [IDL.Vec(Edukasi)], ['query']),
    'getEventsByDate' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getEventsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
    'getMemberProfilesByBusinessName' : IDL.Func(
        [],
        [IDL.Vec(MemberProfile)],
        ['query'],
      ),
    'getMemberProfilesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MemberProfile)],
        ['query'],
      ),
    'getMemberProfilesByCategorySorted' : IDL.Func(
        [],
        [IDL.Vec(MemberProfile)],
        ['query'],
      ),
    'getMembersForAdmin' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
    'getPastEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getPengajuanByKategori' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PengajuanProduk)],
        ['query'],
      ),
    'getPengajuanByKategoriSorted' : IDL.Func(
        [],
        [IDL.Vec(PengajuanProduk)],
        ['query'],
      ),
    'getPengajuanByNamaUsahaSorted' : IDL.Func(
        [],
        [IDL.Vec(PengajuanProduk)],
        ['query'],
      ),
    'getPhotosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Photo)], ['query']),
    'getPhotosByUploadDate' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getProdukByKategori' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProdukAnggota)],
        ['query'],
      ),
    'getProdukByKategoriSorted' : IDL.Func(
        [],
        [IDL.Vec(ProdukAnggota)],
        ['query'],
      ),
    'getProdukByNamaUsahaSorted' : IDL.Func(
        [],
        [IDL.Vec(ProdukAnggota)],
        ['query'],
      ),
    'getSortedAnggotaList' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
    'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerMember' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [MemberId],
        [],
      ),
    'rejectPengajuanProduk' : IDL.Func([PengajuanProdukId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchAnggota' : IDL.Func([IDL.Text], [IDL.Vec(MemberProfile)], ['query']),
    'searchMemberProfilesByBusinessName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MemberProfile)],
        ['query'],
      ),
    'startAdminSession' : IDL.Func([IDL.Text, IDL.Text], [AdminSessionId], []),
    'updateMemberIdNumber' : IDL.Func([MemberId, IDL.Text], [], []),
    'validateAdminSession' : IDL.Func([AdminSessionId], [IDL.Bool], ['query']),
    'verifyMember' : IDL.Func([MemberId, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };