/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminSessionId = bigint;
export interface Article {
  'id' : ArticleId,
  'title' : string,
  'content' : string,
  'date' : bigint,
  'author' : string,
}
export type ArticleId = bigint;
export interface Edukasi {
  'id' : EdukasiId,
  'title' : string,
  'content' : string,
  'date' : bigint,
  'author' : string,
  'image' : [] | [string],
}
export type EdukasiId = bigint;
export interface Event {
  'id' : EventId,
  'title' : string,
  'date' : bigint,
  'description' : string,
  'isUpcoming' : boolean,
  'location' : string,
}
export type EventId = bigint;
export type MemberId = bigint;
export type MemberIdNumber = string;
export interface MemberProfile {
  'id' : MemberId,
  'verified' : boolean,
  'contact' : string,
  'userId' : Principal,
  'name' : string,
  'businessName' : string,
  'description' : string,
  'website' : [] | [string],
  'address' : string,
  'category' : string,
  'products' : Array<string>,
  'memberIdNumber' : [] | [MemberIdNumber],
}
export interface PengajuanProduk {
  'id' : PengajuanProdukId,
  'namaUsaha' : string,
  'foto' : [] | [string],
  'kategori' : string,
  'hubungiSelanjutnya' : [] | [string],
}
export type PengajuanProdukId = bigint;
export interface Photo {
  'id' : PhotoId,
  'url' : string,
  'title' : string,
  'category' : string,
  'uploadDate' : bigint,
}
export type PhotoId = bigint;
export interface ProdukAnggota {
  'id' : ProdukId,
  'namaUsaha' : string,
  'foto' : [] | [string],
  'kategori' : string,
  'hubungiSelanjutnya' : [] | [string],
}
export type ProdukId = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addArticle' : ActorMethod<[string, string, string], ArticleId>,
  'addEdukasi' : ActorMethod<
    [string, string, string, [] | [string]],
    EdukasiId
  >,
  'addEvent' : ActorMethod<[string, string, string, bigint, boolean], EventId>,
  'addPengajuanProduk' : ActorMethod<
    [[] | [string], string, string, [] | [string]],
    PengajuanProdukId
  >,
  'addPhoto' : ActorMethod<[string, string, string], PhotoId>,
  'addProdukAnggota' : ActorMethod<
    [[] | [string], string, string, [] | [string]],
    ProdukId
  >,
  'approvePengajuanProduk' : ActorMethod<[PengajuanProdukId], ProdukId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEdukasi' : ActorMethod<[EdukasiId], undefined>,
  'deleteProdukAnggota' : ActorMethod<[ProdukId], undefined>,
  'editEdukasi' : ActorMethod<
    [EdukasiId, string, string, string, [] | [string]],
    undefined
  >,
  'editProdukAnggota' : ActorMethod<
    [ProdukId, [] | [string], string, string, [] | [string]],
    undefined
  >,
  'endAdminSession' : ActorMethod<[AdminSessionId], undefined>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getAllEdukasi' : ActorMethod<[], Array<Edukasi>>,
  'getAllMemberProfiles' : ActorMethod<[], Array<MemberProfile>>,
  'getAllPengajuanProduk' : ActorMethod<[], Array<PengajuanProduk>>,
  'getAllPhotos' : ActorMethod<[], Array<Photo>>,
  'getAllProdukAnggota' : ActorMethod<[], Array<ProdukAnggota>>,
  'getAnggotaListByCategorySorted' : ActorMethod<
    [string],
    Array<MemberProfile>
  >,
  'getArticlesByDate' : ActorMethod<[], Array<Article>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEdukasiByDate' : ActorMethod<[], Array<Edukasi>>,
  'getEventsByDate' : ActorMethod<[], Array<Event>>,
  'getEventsByLocation' : ActorMethod<[string], Array<Event>>,
  'getMemberProfilesByBusinessName' : ActorMethod<[], Array<MemberProfile>>,
  'getMemberProfilesByCategory' : ActorMethod<[string], Array<MemberProfile>>,
  'getMemberProfilesByCategorySorted' : ActorMethod<[], Array<MemberProfile>>,
  'getMembersForAdmin' : ActorMethod<[], Array<MemberProfile>>,
  'getPastEvents' : ActorMethod<[], Array<Event>>,
  'getPengajuanByKategori' : ActorMethod<[string], Array<PengajuanProduk>>,
  'getPengajuanByKategoriSorted' : ActorMethod<[], Array<PengajuanProduk>>,
  'getPengajuanByNamaUsahaSorted' : ActorMethod<[], Array<PengajuanProduk>>,
  'getPhotosByCategory' : ActorMethod<[string], Array<Photo>>,
  'getPhotosByUploadDate' : ActorMethod<[], Array<Photo>>,
  'getProdukByKategori' : ActorMethod<[string], Array<ProdukAnggota>>,
  'getProdukByKategoriSorted' : ActorMethod<[], Array<ProdukAnggota>>,
  'getProdukByNamaUsahaSorted' : ActorMethod<[], Array<ProdukAnggota>>,
  'getSortedAnggotaList' : ActorMethod<[], Array<MemberProfile>>,
  'getUpcomingEvents' : ActorMethod<[], Array<Event>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerMember' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      [] | [string],
      string,
    ],
    MemberId
  >,
  'rejectPengajuanProduk' : ActorMethod<[PengajuanProdukId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchAnggota' : ActorMethod<[string], Array<MemberProfile>>,
  'searchMemberProfilesByBusinessName' : ActorMethod<
    [string],
    Array<MemberProfile>
  >,
  'startAdminSession' : ActorMethod<[string, string], AdminSessionId>,
  'updateMemberIdNumber' : ActorMethod<[MemberId, string], undefined>,
  'validateAdminSession' : ActorMethod<[AdminSessionId], boolean>,
  'verifyMember' : ActorMethod<[MemberId, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];