/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Photo {
    id: PhotoId;
    url: string;
    title: string;
    category: string;
    uploadDate: bigint;
}
export interface UserProfile {
    name: string;
    email?: string;
    phone?: string;
}
export type ProdukId = bigint;
export type PhotoId = bigint;
export type EventId = bigint;
export interface Article {
    id: ArticleId;
    title: string;
    content: string;
    date: bigint;
    author: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Event {
    id: EventId;
    title: string;
    date: bigint;
    description: string;
    isUpcoming: boolean;
    location: string;
}
export type MemberId = bigint;
export type AdminSessionId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type ArticleId = bigint;
export interface MemberProfile {
    id: MemberId;
    verified: boolean;
    contact: string;
    userId: Principal;
    name: string;
    businessName: string;
    description: string;
    website?: string;
    address: string;
    category: string;
    products: Array<string>;
    memberIdNumber?: MemberIdNumber;
}
export interface PengajuanProduk {
    id: PengajuanProdukId;
    namaUsaha: string;
    foto?: string;
    kategori: string;
    hubungiSelanjutnya?: string;
}
export interface Edukasi {
    id: EdukasiId;
    title: string;
    content: string;
    date: bigint;
    author: string;
    image?: string;
}
export type MemberIdNumber = string;
export type PengajuanProdukId = bigint;
export type EdukasiId = bigint;
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ProdukAnggota {
    id: ProdukId;
    namaUsaha: string;
    foto?: string;
    kategori: string;
    hubungiSelanjutnya?: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addArticle(title: string, content: string, author: string): Promise<ArticleId>;
    addEdukasi(title: string, content: string, author: string, image: string | null): Promise<EdukasiId>;
    addEvent(title: string, description: string, location: string, date: bigint, isUpcoming: boolean): Promise<EventId>;
    addPengajuanProduk(foto: string | null, kategori: string, namaUsaha: string, hubungiSelanjutnya: string | null): Promise<PengajuanProdukId>;
    addPhoto(title: string, category: string, url: string): Promise<PhotoId>;
    addProdukAnggota(foto: string | null, kategori: string, namaUsaha: string, hubungiSelanjutnya: string | null): Promise<ProdukId>;
    approvePengajuanProduk(pengajuanId: PengajuanProdukId): Promise<ProdukId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteEdukasi(id: EdukasiId): Promise<void>;
    deleteProdukAnggota(id: ProdukId): Promise<void>;
    editEdukasi(id: EdukasiId, title: string, content: string, author: string, image: string | null): Promise<void>;
    editProdukAnggota(id: ProdukId, foto: string | null, kategori: string, namaUsaha: string, hubungiSelanjutnya: string | null): Promise<void>;
    endAdminSession(sessionId: AdminSessionId): Promise<void>;
    getAllArticles(): Promise<Array<Article>>;
    getAllEdukasi(): Promise<Array<Edukasi>>;
    getAllMemberProfiles(): Promise<Array<MemberProfile>>;
    getAllPengajuanProduk(): Promise<Array<PengajuanProduk>>;
    getAllPhotos(): Promise<Array<Photo>>;
    getAllProdukAnggota(): Promise<Array<ProdukAnggota>>;
    getAnggotaListByCategorySorted(category: string): Promise<Array<MemberProfile>>;
    getArticlesByDate(): Promise<Array<Article>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEdukasiByDate(): Promise<Array<Edukasi>>;
    getEventsByDate(): Promise<Array<Event>>;
    getEventsByLocation(location: string): Promise<Array<Event>>;
    getMemberProfilesByBusinessName(): Promise<Array<MemberProfile>>;
    getMemberProfilesByCategory(category: string): Promise<Array<MemberProfile>>;
    getMemberProfilesByCategorySorted(): Promise<Array<MemberProfile>>;
    getMembersForAdmin(): Promise<Array<MemberProfile>>;
    getPastEvents(): Promise<Array<Event>>;
    getPengajuanByKategori(category: string): Promise<Array<PengajuanProduk>>;
    getPengajuanByKategoriSorted(): Promise<Array<PengajuanProduk>>;
    getPengajuanByNamaUsahaSorted(): Promise<Array<PengajuanProduk>>;
    getPhotosByCategory(category: string): Promise<Array<Photo>>;
    getPhotosByUploadDate(): Promise<Array<Photo>>;
    getProdukByKategori(category: string): Promise<Array<ProdukAnggota>>;
    getProdukByKategoriSorted(): Promise<Array<ProdukAnggota>>;
    getProdukByNamaUsahaSorted(): Promise<Array<ProdukAnggota>>;
    getSortedAnggotaList(): Promise<Array<MemberProfile>>;
    getUpcomingEvents(): Promise<Array<Event>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerMember(name: string, businessName: string, description: string, contact: string, category: string, products: Array<string>, website: string | null, address: string): Promise<MemberId>;
    rejectPengajuanProduk(pengajuanId: PengajuanProdukId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchAnggota(searchTerm: string): Promise<Array<MemberProfile>>;
    searchMemberProfilesByBusinessName(searchTerm: string): Promise<Array<MemberProfile>>;
    startAdminSession(username: string, password: string): Promise<AdminSessionId>;
    updateMemberIdNumber(memberId: MemberId, memberIdNumber: string): Promise<void>;
    validateAdminSession(sessionId: AdminSessionId): Promise<boolean>;
    verifyMember(memberId: MemberId, verified: boolean): Promise<void>;
}
import type { Edukasi as _Edukasi, EdukasiId as _EdukasiId, MemberId as _MemberId, MemberIdNumber as _MemberIdNumber, MemberProfile as _MemberProfile, PengajuanProduk as _PengajuanProduk, PengajuanProdukId as _PengajuanProdukId, ProdukAnggota as _ProdukAnggota, ProdukId as _ProdukId, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addArticle(arg0: string, arg1: string, arg2: string): Promise<ArticleId> {
        if (this.processError) {
            try {
                const result = await this.actor.addArticle(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addArticle(arg0, arg1, arg2);
            return result;
        }
    }
    async addEdukasi(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<EdukasiId> {
        if (this.processError) {
            try {
                const result = await this.actor.addEdukasi(arg0, arg1, arg2, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEdukasi(arg0, arg1, arg2, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg3));
            return result;
        }
    }
    async addEvent(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: boolean): Promise<EventId> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addPengajuanProduk(arg0: string | null, arg1: string, arg2: string, arg3: string | null): Promise<PengajuanProdukId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPengajuanProduk(to_candid_opt_n8(this.uploadFile, this.downloadFile, arg0), arg1, arg2, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPengajuanProduk(to_candid_opt_n8(this.uploadFile, this.downloadFile, arg0), arg1, arg2, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg3));
            return result;
        }
    }
    async addPhoto(arg0: string, arg1: string, arg2: string): Promise<PhotoId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPhoto(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPhoto(arg0, arg1, arg2);
            return result;
        }
    }
    async addProdukAnggota(arg0: string | null, arg1: string, arg2: string, arg3: string | null): Promise<ProdukId> {
        if (this.processError) {
            try {
                const result = await this.actor.addProdukAnggota(to_candid_opt_n8(this.uploadFile, this.downloadFile, arg0), arg1, arg2, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProdukAnggota(to_candid_opt_n8(this.uploadFile, this.downloadFile, arg0), arg1, arg2, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg3));
            return result;
        }
    }
    async approvePengajuanProduk(arg0: PengajuanProdukId): Promise<ProdukId> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePengajuanProduk(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePengajuanProduk(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async deleteEdukasi(arg0: EdukasiId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEdukasi(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEdukasi(arg0);
            return result;
        }
    }
    async deleteProdukAnggota(arg0: ProdukId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProdukAnggota(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProdukAnggota(arg0);
            return result;
        }
    }
    async editEdukasi(arg0: EdukasiId, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editEdukasi(arg0, arg1, arg2, arg3, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editEdukasi(arg0, arg1, arg2, arg3, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg4));
            return result;
        }
    }
    async editProdukAnggota(arg0: ProdukId, arg1: string | null, arg2: string, arg3: string, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editProdukAnggota(arg0, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg1), arg2, arg3, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editProdukAnggota(arg0, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg1), arg2, arg3, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg4));
            return result;
        }
    }
    async endAdminSession(arg0: AdminSessionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endAdminSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endAdminSession(arg0);
            return result;
        }
    }
    async getAllArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArticles();
            return result;
        }
    }
    async getAllEdukasi(): Promise<Array<Edukasi>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEdukasi();
                return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEdukasi();
            return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllMemberProfiles(): Promise<Array<MemberProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMemberProfiles();
                return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMemberProfiles();
            return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllPengajuanProduk(): Promise<Array<PengajuanProduk>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPengajuanProduk();
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPengajuanProduk();
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllPhotos(): Promise<Array<Photo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPhotos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPhotos();
            return result;
        }
    }
    async getAllProdukAnggota(): Promise<Array<ProdukAnggota>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProdukAnggota();
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProdukAnggota();
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAnggotaListByCategorySorted(arg0: string): Promise<Array<MemberProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnggotaListByCategorySorted(arg0);
                return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnggotaListByCategorySorted(arg0);
            return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getArticlesByDate(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticlesByDate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticlesByDate();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getEdukasiByDate(): Promise<Array<Edukasi>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEdukasiByDate();
                return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEdukasiByDate();
            return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getEventsByDate(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByDate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByDate();
            return result;
        }
    }
    async getEventsByLocation(arg0: string): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByLocation(arg0);
            return result;
        }
    }
    async getMemberProfilesByBusinessName(): Promise<Array<MemberProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberProfilesByBusinessName();
                return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberProfilesByBusinessName();
            return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMemberProfilesByCategory(arg0: string): Promise<Array<MemberProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberProfilesByCategory(arg0);
                return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberProfilesByCategory(arg0);
            return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMemberProfilesByCategorySorted(): Promise<Array<MemberProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberProfilesByCategorySorted();
                return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberProfilesByCategorySorted();
            return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMembersForAdmin(): Promise<Array<MemberProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembersForAdmin();
                return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembersForAdmin();
            return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPastEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPastEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPastEvents();
            return result;
        }
    }
    async getPengajuanByKategori(arg0: string): Promise<Array<PengajuanProduk>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPengajuanByKategori(arg0);
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPengajuanByKategori(arg0);
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPengajuanByKategoriSorted(): Promise<Array<PengajuanProduk>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPengajuanByKategoriSorted();
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPengajuanByKategoriSorted();
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPengajuanByNamaUsahaSorted(): Promise<Array<PengajuanProduk>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPengajuanByNamaUsahaSorted();
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPengajuanByNamaUsahaSorted();
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPhotosByCategory(arg0: string): Promise<Array<Photo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotosByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotosByCategory(arg0);
            return result;
        }
    }
    async getPhotosByUploadDate(): Promise<Array<Photo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotosByUploadDate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotosByUploadDate();
            return result;
        }
    }
    async getProdukByKategori(arg0: string): Promise<Array<ProdukAnggota>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProdukByKategori(arg0);
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProdukByKategori(arg0);
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProdukByKategoriSorted(): Promise<Array<ProdukAnggota>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProdukByKategoriSorted();
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProdukByKategoriSorted();
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProdukByNamaUsahaSorted(): Promise<Array<ProdukAnggota>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProdukByNamaUsahaSorted();
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProdukByNamaUsahaSorted();
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSortedAnggotaList(): Promise<Array<MemberProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedAnggotaList();
                return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedAnggotaList();
            return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUpcomingEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingEvents();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerMember(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<string>, arg6: string | null, arg7: string): Promise<MemberId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerMember(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerMember(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg6), arg7);
            return result;
        }
    }
    async rejectPengajuanProduk(arg0: PengajuanProdukId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPengajuanProduk(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPengajuanProduk(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async searchAnggota(arg0: string): Promise<Array<MemberProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAnggota(arg0);
                return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAnggota(arg0);
            return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async searchMemberProfilesByBusinessName(arg0: string): Promise<Array<MemberProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMemberProfilesByBusinessName(arg0);
                return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMemberProfilesByBusinessName(arg0);
            return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async startAdminSession(arg0: string, arg1: string): Promise<AdminSessionId> {
        if (this.processError) {
            try {
                const result = await this.actor.startAdminSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startAdminSession(arg0, arg1);
            return result;
        }
    }
    async updateMemberIdNumber(arg0: MemberId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemberIdNumber(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemberIdNumber(arg0, arg1);
            return result;
        }
    }
    async validateAdminSession(arg0: AdminSessionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAdminSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAdminSession(arg0);
            return result;
        }
    }
    async verifyMember(arg0: MemberId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyMember(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Edukasi_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Edukasi): Edukasi {
    return from_candid_record_n13(uploadFile, downloadFile, value);
}
function from_candid_MemberProfile_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberProfile): MemberProfile {
    return from_candid_record_n17(uploadFile, downloadFile, value);
}
function from_candid_PengajuanProduk_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PengajuanProduk): PengajuanProduk {
    return from_candid_record_n21(uploadFile, downloadFile, value);
}
function from_candid_ProdukAnggota_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProdukAnggota): ProdukAnggota {
    return from_candid_record_n24(uploadFile, downloadFile, value);
}
function from_candid_UserProfile_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n27(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MemberIdNumber]): MemberIdNumber | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n26(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EdukasiId;
    title: string;
    content: string;
    date: bigint;
    author: string;
    image: [] | [string];
}): {
    id: EdukasiId;
    title: string;
    content: string;
    date: bigint;
    author: string;
    image?: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        date: value.date,
        author: value.author,
        image: record_opt_to_undefined(from_candid_opt_n14(uploadFile, downloadFile, value.image))
    };
}
function from_candid_record_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MemberId;
    verified: boolean;
    contact: string;
    userId: Principal;
    name: string;
    businessName: string;
    description: string;
    website: [] | [string];
    address: string;
    category: string;
    products: Array<string>;
    memberIdNumber: [] | [_MemberIdNumber];
}): {
    id: MemberId;
    verified: boolean;
    contact: string;
    userId: Principal;
    name: string;
    businessName: string;
    description: string;
    website?: string;
    address: string;
    category: string;
    products: Array<string>;
    memberIdNumber?: MemberIdNumber;
} {
    return {
        id: value.id,
        verified: value.verified,
        contact: value.contact,
        userId: value.userId,
        name: value.name,
        businessName: value.businessName,
        description: value.description,
        website: record_opt_to_undefined(from_candid_opt_n14(uploadFile, downloadFile, value.website)),
        address: value.address,
        category: value.category,
        products: value.products,
        memberIdNumber: record_opt_to_undefined(from_candid_opt_n18(uploadFile, downloadFile, value.memberIdNumber))
    };
}
function from_candid_record_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PengajuanProdukId;
    namaUsaha: string;
    foto: [] | [string];
    kategori: string;
    hubungiSelanjutnya: [] | [string];
}): {
    id: PengajuanProdukId;
    namaUsaha: string;
    foto?: string;
    kategori: string;
    hubungiSelanjutnya?: string;
} {
    return {
        id: value.id,
        namaUsaha: value.namaUsaha,
        foto: record_opt_to_undefined(from_candid_opt_n14(uploadFile, downloadFile, value.foto)),
        kategori: value.kategori,
        hubungiSelanjutnya: record_opt_to_undefined(from_candid_opt_n14(uploadFile, downloadFile, value.hubungiSelanjutnya))
    };
}
function from_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProdukId;
    namaUsaha: string;
    foto: [] | [string];
    kategori: string;
    hubungiSelanjutnya: [] | [string];
}): {
    id: ProdukId;
    namaUsaha: string;
    foto?: string;
    kategori: string;
    hubungiSelanjutnya?: string;
} {
    return {
        id: value.id,
        namaUsaha: value.namaUsaha,
        foto: record_opt_to_undefined(from_candid_opt_n14(uploadFile, downloadFile, value.foto)),
        kategori: value.kategori,
        hubungiSelanjutnya: record_opt_to_undefined(from_candid_opt_n14(uploadFile, downloadFile, value.hubungiSelanjutnya))
    };
}
function from_candid_record_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    phone: [] | [string];
}): {
    name: string;
    email?: string;
    phone?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n14(uploadFile, downloadFile, value.email)),
        phone: record_opt_to_undefined(from_candid_opt_n14(uploadFile, downloadFile, value.phone))
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Edukasi>): Array<Edukasi> {
    return value.map((x)=>from_candid_Edukasi_n12(uploadFile, downloadFile, x));
}
function from_candid_vec_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemberProfile>): Array<MemberProfile> {
    return value.map((x)=>from_candid_MemberProfile_n16(uploadFile, downloadFile, x));
}
function from_candid_vec_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PengajuanProduk>): Array<PengajuanProduk> {
    return value.map((x)=>from_candid_PengajuanProduk_n20(uploadFile, downloadFile, x));
}
function from_candid_vec_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProdukAnggota>): Array<ProdukAnggota> {
    return value.map((x)=>from_candid_ProdukAnggota_n23(uploadFile, downloadFile, x));
}
function to_candid_UserProfile_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n31(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_opt_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    phone?: string;
}): {
    name: string;
    email: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_variant_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
